name: Dissect CI
on: [push, pull_request, workflow_dispatch]

jobs: 
  ci:
    uses: fox-it/dissect-workflow-templates/.github/workflows/dissect-ci-template.yml@main
    with:
      run_tests: false
    secrets: inherit
